.TH FSIO-RT11 1 "Jun 25,2019" "FFS I/O - RT-11"
.SH NAME
fsio-rt11 \- Foreign File System I/O - RT-11
.br
.SH DESCRIPTION
\fBfsio\fP allows access to RT-11 file systems using the file system type
"\fIrt11\fP"
.br
.SH RT-11 VERSIONS
There were 5 major versions of RT-11 released. Versions 1 and 2 did not use
the home block (block 1) to indicate that the on-disk file structure was RT-11
format. The remaining 3 versions wrote a signature on the home block
including the file system version in use. In order to access a version 1 or
version 2 container file, the \fI"-f"\fP switch must be used on the
\fI"mount"\fP command to force \fBfsio\fP
to bypass the home block checks. While \fBfsio\fP will use a set of
heuristics to verify the integrity of the RT-11 file structure it is possible
that an invalid file structure will satisfy the checks and cause \fBfsio\fP to
fail. Do not use the \fI"-f"\fP switch other than to mount version 1 or
version 2 file systems.

.br
The VMS exchange utility may be used to initialize an RT-11 volume but writes
it's own unique signature in the home block. \fBfsio\fP is able to correctly
handle this signature.
.br
.SH RT-11 PHYSICAL DISKS
RT-11 uses a file system block size of 512 bytes and most disk type either
have a block size of 512 bytes or use 2 contiguous blocks or 256 bytes each.
Floppy diskettes, RX01 and RX02 drives, use small sectors size and for
performance reason, adjacent logical sectors are interleaved within the same
track. When mounting a floppy diskette, the \fI"-f type"\fP must be used so
that \fIfsio\fP can determine the interleaving used. In this case "type"
should be either "rx01" or "rx02".
.SH LOGICAL DISKS
\fBfsio\fP can be used to access an RT-11 logical disk if the file has been
copied to the host file system.
.SH WILDCARD CHARACTERS
The wildcard character \fI'%'\fP may be used to match a single character in a
filename or type. The wildcard character \fI'*'\fP may be used to match
zero or more characters in a filename or type. Wildcard characters are only
valid with the \fIdir\fP command.
.br
.SH NEWFS OPERATION
\fInewfs\fP creates a blank MSCP image (32MB, 65535 blocks) with a single
partition which can be accessed via the DU device (rq in SIMH). If the
\fI"-t type"\fP switch is present, a smaller container file will be created
depending on the type of device specified:
.br
.RS
.TP
\fIrk05\fP    \- RK05 image (2.5MB, 4800 blocks)
.br
.TP
\fIrl01\fP    \- RL01 image (5MB, 10240 blocks)
.br
.TP
\fIrl02\fP    \- RL02 image (10MB, 20480 blocks)
.br
.TP
\fIrx01\fP    \- RX01 floopy image (256KB, 2002 sectors of 128 bytes)
.br
.TP
\fIrx02\fP    \- RX02 floopy image (512KB, 2002 sectors of 256 bytes)
.br
.RE

The "\fI-e extra\fP" switch, where "extra" is a number in the range 0 - 63,
may be used to create file systems with "extra" additional bytes available to
each directory entry. \fIfsio\fP will silently round up the value to make it
an even number required by RT-11. By default, \fInewfs\fP will create file
systems with no additional bytes for each directory entry.
.SH COPY OPERATION
When copying in ASCII mode, \fBfsio\fP will normally write ^Z (octal 032) to
indicate the end-of-file. Some utilities, such as FLX on RSX-11, cannot
handle ^Z in the middle of a formatted ASCII file. The \fI"-p"\fP switch
may be used on a copy operation to skip writing the ^Z and pad the file with
NULLs up to the next block boundary if this occurs.
.br
.SH SET OPERATION
No \fIset\fP commands are currently supported.
.SH SEE ALSO
.BR fsio (1)
.BR fsio-dos11 (1)
.BR fsio-dosmt (1)
.BR fsio-os8 (1)
.SH AUTHOR
John Forecast, <john@forecast.name>
.br
