;;;;;
;
; Test delimiters of .ASCII and .ASCIZ

CR = 13.
LF = 10.
SOH = 1

        .asciz <cr><lf>/<SOH>/          ; 2 bytes and a string
        .asciz /<cr><lf><SOH>/          ; only a string
        .asciz |<cr><lf><SOH>|          ; the same string
        .ascii <cr><lf><SOH>            ; 3 bytes

        .asciz ;ABC;/DEF/               ; ABCDEF, not recommended practice
        .asciz /ABC/;DEF;               ; ABC, not recommended practice
        .asciz /ABC/=DEF=               ; ABCDEF, not recommended practice
        .asciz &###&                    ; another weird delimiter
        .asciz =DEF=                    ; syntax error: assignment
        .asciz =###=                    ; syntax error: assignment
	.even
        .asciz :SOH:                    ; syntax error: colon not allowed
        .asciz :###:                    ; syntax error: colon not allowed
        .asciz ^###^                    ; previous versions of this macro11
	; used ^/.../ quoting as an extension; however this should be ^...^.
