        .macro  tstarg a1,a2,a3,a4
        .narg   label
        .endm

start:  tstarg          ; 0 args
        tstarg   123    ; 1 arg
        tstarg   1,     ; 2 args
        tstarg   ,2     ; 2 args
        tstarg   ,      ; 2 args
        tstarg   ,,     ; 3 args
        tstarg   1,,    ; 3 args
        tstarg   ,,3    ; 3 args
        tstarg   1,,3   ; 3 args
        tstarg   1,2,3  ; 3 args
